### PR TITLE
fix: create shortcut in specific env

### PR DESCRIPTION
**Pull request by ZianTT**
it cannot create desktop shortcut if the desktop is modified

### CODE REVIEW

**Review by RinLit-233-shiroko — APPROVED** [review]
thank you for maintaining this project!ヾ(≧▽≦*)o

**Comment by ZianTT** [comment]
But it should be merged instead of close...?

**Comment by ZianTT** [comment]
I have merged the changes in my fork.

**Comment by ZianTT** [comment]
@RinLit-233-shiroko

**Pull request closed without merging**
